import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { challenges, useActivity } from '@/features/activity/activity-context';
import { Button, Icon, palette, PageTitle, s, Screen, Section } from '@/features/activity/ui';

export default function ProgressScreen() {
  const { completed, points } = useActivity();
  const minutes = challenges.filter(item => completed.includes(item.id)).reduce((sum, item) => sum + item.minutes, 0);
  const dailyCount = challenges.slice(0, 3).filter(item => completed.includes(item.id)).length;
  const today = (new Date().getDay() + 6) % 7;
  return <Screen>
    <PageTitle eyebrow="ЖИЖИГ АЛХМУУД НЭМЭГДСЭЭР" title="Чиний ахиц" subtitle="Бусадтай биш, өчигдрийн өөртэйгөө уралд." />
    <View style={styles.summary}><View style={styles.ring}><Text style={styles.ringNumber}>{dailyCount}<Text style={styles.ringSmall}>/3</Text></Text><Text style={styles.ringLabel}>ӨНӨӨДӨР</Text></View><View style={{ flex: 1, gap: 10 }}><View style={s.pill}><Text style={s.pillText}>{dailyCount === 3 ? 'ЗОРИЛГОДОО ХҮРЛЭЭ' : 'ӨДРИЙН ЗОРИЛГО'}</Text></View><Text style={s.sectionTitle}>{dailyCount === 3 ? 'Чи чадлаа!' : 'Алхам бүр үнэ цэнтэй.'}</Text><Text style={s.caption}>{dailyCount === 3 ? 'Өнөөдрийн 3 сорилтоо бүгдийг дуусгалаа.' : `${3 - dailyCount} жижиг сорилт чамайг хүлээж байна.`}</Text></View></View>
    <View style={styles.metrics}>{[{ value: points, label: 'Цуглуулсан XP', icon: 'challenge' as const, color: palette.lime }, { value: completed.length, label: 'Дууссан сорилт', icon: 'check' as const, color: '#C6B8F5' }, { value: minutes, label: 'Зарцуулсан мин', icon: 'clock' as const, color: '#F2BD96' }].map(item => <View style={styles.metric} key={item.label}><Icon name={item.icon} color={item.color} size={22} /><Text style={styles.metricNumber}>{item.value}</Text><Text style={styles.metricLabel}>{item.label}</Text></View>)}</View>
    <View style={s.card}><View style={s.between}><Text style={s.sectionTitle}>Энэ долоо хоног</Text><Text style={s.caption}>Сорилт</Text></View><View style={styles.chart}>{['Да', 'Мя', 'Лх', 'Пү', 'Ба', 'Бя', 'Ня'].map((day, index) => <View key={day} style={styles.barColumn}><Text style={[s.caption, index === today && { color: palette.lime }]}>{index === today ? completed.length : '–'}</Text><View style={styles.barTrack}><View style={[styles.bar, { height: index === today ? `${Math.max(completed.length / challenges.length * 100, 3)}%` : 3, backgroundColor: index === today ? palette.lime : '#414A36' }]} /></View><Text style={[s.caption, index === today && { color: palette.lime }]}>{day}</Text></View>)}</View><Text style={s.caption}>Өнөөдрийн хийсэн сорилтууд энд нэмэгдэнэ.</Text></View>
    <View style={{ gap: 16 }}><Section title="Чиний тэмдгүүд" /><View style={styles.badges}>{[{ icon: 'sun' as const, label: 'Эхний алхам', threshold: 1, sub: '1 сорилт' }, { icon: 'trophy' as const, label: 'Сайн хэмнэл', threshold: 3, sub: '3 сорилт' }, { icon: 'flame' as const, label: 'Бүгдийг чадна', threshold: 6, sub: '6 сорилт' }].map(item => { const unlocked = completed.length >= item.threshold; return <View key={item.label} style={styles.badge}><View style={[styles.badgeIcon, unlocked && { backgroundColor: '#354125', borderColor: palette.lime }]}><Icon name={item.icon} size={29} color={unlocked ? palette.lime : '#697260'} /></View><Text style={[styles.badgeLabel, unlocked && { color: palette.text }]}>{item.label}</Text><Text style={s.tiny}>{unlocked ? 'НЭЭГДСЭН ✓' : item.sub}</Text></View>; })}</View></View>
    <Button label="Дараагийн сорилтоо сонгох" onPress={() => router.navigate('/explore')} />
  </Screen>;
}
const styles = StyleSheet.create({
  summary: { flexDirection: 'row', alignItems: 'center', backgroundColor: palette.card, borderRadius: 24, padding: 20, gap: 20 }, ring: { width: 113, height: 113, borderRadius: 60, borderWidth: 7, borderColor: palette.lime, justifyContent: 'center', alignItems: 'center', gap: 4 }, ringNumber: { color: palette.text, fontSize: 34, fontWeight: '700' }, ringSmall: { fontSize: 18, color: palette.muted }, ringLabel: { color: palette.muted, fontSize: 8, letterSpacing: 1 },
  metrics: { flexDirection: 'row', gap: 9 }, metric: { flex: 1, alignItems: 'center', gap: 10, paddingVertical: 19, paddingHorizontal: 3, backgroundColor: palette.card, borderRadius: 20 }, metricNumber: { color: palette.text, fontSize: 27, fontWeight: '700' }, metricLabel: { color: palette.muted, fontSize: 9, textAlign: 'center' },
  chart: { flexDirection: 'row', gap: 13, height: 175 }, barColumn: { flex: 1, alignItems: 'center', gap: 10 }, barTrack: { flex: 1, width: '100%', backgroundColor: '#272D22', borderRadius: 8, justifyContent: 'flex-end', overflow: 'hidden' }, bar: { width: '100%', borderRadius: 8, minHeight: 3 },
  badges: { flexDirection: 'row', gap: 8 }, badge: { flex: 1, alignItems: 'center', gap: 10 }, badgeIcon: { width: 72, height: 78, borderRadius: 25, backgroundColor: palette.card, borderWidth: 1, borderColor: palette.line, justifyContent: 'center', alignItems: 'center' }, badgeLabel: { color: palette.muted, fontSize: 11, fontWeight: '600', textAlign: 'center' },
});
